repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: end-of-file-fixer
        exclude: .devcontainer/devcontainer-lock.json
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.2.2"
    hooks:
      - id: ruff
