[project]
name = "dragonfly-loader"
version = "2.0.0"
requires-python = ">=3.11,<3.13"
description = "Loads all the packages from the PyPI RSS feed into the Dragonfly API"
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
repository = "https://github.com/vipyrsec/dragonfly-loader/"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic.dependencies]
file = ["requirements/requirements.txt"]

[tool.setuptools.dynamic.optional-dependencies]
dev = { file = ["requirements/requirements-dev.txt"] }
tests = { file = ["requirements/requirements-tests.txt"] }
docs = { file = ["requirements/requirements-docs.txt"] }

[tool.black]
target-version = ["py312"]
line-length = 120

[tool.ruff]
target-version = "py312"
line-length = 120
select = ["ALL"]

[tool.ruff.extend-per-file-ignores]
"tests/*" = [
    "INP001", # (File `tests/*.py` is part of an implicit namespace package. Add an `__init__.py`.) - Tests are not modules
    "S101", # (Use of `assert` detected) - Yes, that's the point
    "PT004", # (Fixture `*` does not return anything, add leading underscore) - Used for pytest fixtures
    "ARG001", # (Unused function argument: `*`) - Used for pytest fixtures
]

[tool.ruff.pydocstyle]
convention = "numpy"
