name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0

  test:
    needs: lint
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@41518576ed6c499ed3e68d5cbceaeaa50abd471a # v14.1.0
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
